# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_name=Particulate
mod_version=1.0.6+1.21.11
maven_group=com.dunnewortel.particulate
archives_base_name=particulate

# Dependencies
fabric_version=0.141.3+1.21.11
owo_version=0.13.0+1.21.11
seasons_version=2.4.2+1.21